inherit_gem:
  ruboconfig: rubocop.yml

StringLiterals:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 24

Lint/RescueWithoutErrorClass:
  Exclude:
    - "*/**/*_spec.rb"
